package com.scheible.gwt.reduced.client.framework.rest.proxy;

import com.scheible.gwt.reduced.shared.framework.util.ShouldBeAutoGenerated;
import com.scheible.gwt.reduced.client.framework.rest.AjaxResult;
import com.scheible.gwt.reduced.shared.GridDataDto;
import com.scheible.gwt.reduced.shared.TitleDto;
import com.scheible.gwt.reduced.shared.TestService;
import com.scheible.gwt.reduced.shared.framework.rest.RestResult;

/**
 *
 * @author sj
 */
@ShouldBeAutoGenerated
public class TestServiceProxy implements TestService {

    @Override
    public RestResult<TitleDto> getTitle() {
        return new AjaxResult<>("/title");
    }

    @Override
    public RestResult<GridDataDto> getGridData() {
        return new AjaxResult<>("/grid-data");
    }
}
