package com.scheible.gwt.reduced.shared;

import com.scheible.gwt.reduced.shared.framework.util.ShouldBeAutoGenerated;

/**
 *
 * @author sj
 */
@ShouldBeAutoGenerated
public class Iso8601DateTimeDtoMeta {
    
    public static final String CLASS_NAME = "com.scheible.gwt.reduced.shared.Iso8601DateTimeDto";
}
