package com.scheible.gwt.reduced.shared;

import com.scheible.gwt.reduced.shared.framework.util.ShouldBeAutoGenerated;

/**
 *
 * @author sj
 */
@ShouldBeAutoGenerated
public class MoneyAmountDtoMeta {
    
    public static final String CLASS_NAME = "com.scheible.gwt.reduced.shared.MoneyAmountDto";
}
